### ISSUE TITLE
When receive loaded event visuall stills fetching data

### ISSUE THREAD

**Issue by jordiruiz** [Microsoft/PowerBI-JavaScript#46] opened 2016-09-06 05:20 UTC
I have an embedded report with direct query, and when a receive the loaded callback some visuals are not loaded.

**Comment by pkwiecien** [comment] 2016-09-06 17:21
Can you still reproduce the issue?
If so, each visual that is not loaded, should have correlation id associated with the error. Would be great if you can provide us that information and we can further investigate the error.

**Comment by jordiruiz** [comment] 2016-09-06 18:26
I don't see any error, in fact visuals are loaded it's just that when loaded event fires visual are not yet loaded. 

![powerbi_loaded](https://cloud.githubusercontent.com/assets/2950890/18285743/0fb5735a-7470-11e6-9248-c3a38579c731.gif)

**Comment by mattmazzola** [comment] 2016-09-06 19:51
This seems like a non-issue then.  From my understanding, the loaded event was intended to only indicate that the application has been initialized and is ready to receive future commands from the host.  It was not intended to indicate that all visuals have finished loading.  This would be dependent on each different type of visual since they could take more or less time to render and I'm not sure there is a way to know when they have all finished. Also, because you are using Direct Query I think the load time of visuals would depend on your connection to your data.

@pkwiecien Is the above statement correct that the loaded event is not intended to occur after visuals have finished rendering?

Also, even if we could defer the loaded event until visuals have finished loading, i'm not sure this would be the correct behavior for other use cases.  If it's possible to get this information I would likely have to be in a separate event.

**Comment by wbreza** [comment] 2016-09-06 19:57
Agreed with @mattmazzola here.  This event is was intended to be a notification of when the report is ready to receive new messages, not that the UI has completely loaded.  

It's a great suggestion and we should add it to the issues backlog as a future enhancement.

**Comment by pkwiecien** [comment] 2016-09-06 20:19
@mattmazzola That's correct, **_loaded_** event is not intended to indicate that visuals are loaded. 
As @wbreza pointed out, we could add a new event for visual loaded as a future enhancement.,

**Comment by jordiruiz** [comment] 2016-09-06 21:04
Ok, thank you.

Yes, it will be good to notify when the UI is fully loaded. I put a print button but if user click quickly some of the visual are not displayed in the browser print dialog, by now I will put a delay before present the print dialog.

**Comment by mattmazzola** [comment] 2016-09-06 22:11
Closing this since `loaded` is working as designed. Opened #47 for further discussion on possible new event.

**Closed by mattmazzola** 2016-09-06 22:11 UTC
