### ISSUE TITLE
PowerBI.JavaScript v2.0.0 loading modules errors

### ISSUE THREAD

**Issue by melzoghbi** [Microsoft/PowerBI-JavaScript#72] opened 2016-10-13 15:49 UTC
I have installed latest power bi NuGet packages in an asp.net MVC project. Here are the installed packages with their versions:

```
 <package id="Microsoft.PowerBI.Api" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.PowerBI.Core" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.PowerBI.JavaScript" version="2.0.0" targetFramework="net452" />
```

When i try to build my project, i get these errors:

![pbieerrorinvscapture](https://cloud.githubusercontent.com/assets/11993393/19356180/f29b7020-913a-11e6-8c82-46bb88f359ba.PNG)

It seems that there is a conflict betweek TS tools i have (ver. 2.0.3) and PBI JS NuGet packages. any idea how to resolve this?

Thanks

**Comment by shand-obs** [comment] 2016-10-17 14:31
These are just errors with the TypeScript definition file that was included with the nuget package. You don't need that file if you are using vanilla JavaScript; exclude the powerbi.d.ts file from your project and the errors will go away.

If you want to use TypeScript, you'll have to work around the missing type definition files by:
- installing the JavaScript api using npm and then copy the missing .d.ts files
- OR making your own type definitions
- OR don't use any type definitions and just declare the types as any (which, of course, defeats the purpose of TypeScript).

**Comment by ali-hamud** [comment] 2016-10-27 21:15
Hi @melzoghbi,
Did the answer above solved your problem?

**Comment by JohnGalt1717** [comment] 2016-10-28 14:20
This obviously isn't a good solution because the bower package also doesn't work and there is no "Typings" image that I can find that will deploy the typings for Powerbi properly. 

This needs to be corrected so that typescript definitions are deployed correctly using typings and NOT through any of the other ways to install.

**Comment by ali-hamud** [comment] 2016-10-28 14:41
I think we should provide another package, Microsoft.PowerBI.TypeScript package for typescript users.

**Comment by JohnGalt1717** [comment] 2016-10-28 14:49
It shouldn't be a package in npm etc. It should be a package in Typings which is what everyone using Typescript uses to get the definitions for 3rd party libraries that they're using.

**Comment by shand-obs** [comment] 2016-11-03 16:03
When PowerBI updates to TypeScript 2.0 that won't be entirely true. [TypeScript is moving typings to npm](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/).

**Comment by ali-hamud** [comment] 2017-02-13 09:34
Duplicate of [https://github.com/Microsoft/PowerBI-JavaScript/issues/129](https://github.com/Microsoft/PowerBI-JavaScript/issues/129)

I will close this as duplicate. please keep updated on the other thread.

**Closed by ali-hamud** 2017-02-13 09:34 UTC
Labels: enhancement
