### ISSUE TITLE
https://app.powerbi.com/donutChartVisuals.js not found

### ISSUE THREAD

**Issue by JonJam** [Microsoft/PowerBI-JavaScript#241] opened 2017-08-21 10:58 UTC
I am sure this isn't the place to post this issue, but creating for awareness.

I am embedding a Pie Chart into a page and today (21/8/17) the pie chart isn't displaying.

Looking at the Chrome Dev Tools I have spotted this:

![image](https://user-images.githubusercontent.com/1730684/29516331-e96e885c-8667-11e7-929d-c7ba74673364.png)

This was working on 18/8/17.

**Comment by ali-hamud** [comment] 2017-08-22 07:35
Hi,
is it the native Pie chart of Power BI?

**Comment by JonJam** [comment] 2017-08-22 07:43
@ali-hamud Yes it is.

**Comment by ali-hamud** [comment] 2017-08-22 09:10
can you say if you are embedding a tile, report or dashboard?

**Comment by JonJam** [comment] 2017-08-22 09:11
@ali-hamud I am embedding a tile.

**Comment by ali-hamud** [comment] 2017-08-22 09:12
Ok, I got a repro.
I will mark it as bug and update on ETA when I have it.

**Comment by JonJam** [comment] 2017-08-22 09:13
Thank you @ali-hamud

**Comment by ArinaHantsis** [comment] 2017-08-23 13:58
@JonJam, fix for this issue expected to reach production on Aug 31st.
Please let us know in case you encounter additional issues.

**Comment by ali-hamud** [comment] 2017-11-01 21:39
Hi @JonJam 
Fix should be in production since Aug 31st.
Please re-open if the problem is not solved.

**Closed by ali-hamud** 2017-11-01 21:39 UTC
Labels: bug
