### ISSUE TITLE
Export Data don't work

### ISSUE THREAD

**Issue by jordiruiz** [Microsoft/PowerBI-JavaScript#102] opened 2016-11-25 08:39 UTC
When I click on export data from a visual the report becomes gray and do nothing

![image](https://cloud.githubusercontent.com/assets/2950890/20619112/04d1596a-b2f3-11e6-8d42-480d96870af5.png)

![image](https://cloud.githubusercontent.com/assets/2950890/20619122/157d4a30-b2f3-11e6-8c77-ba81d1ff3ee9.png)

**Comment by wasp127** [comment] 2016-11-28 22:52
Same exact issue on my end. I have also seen multiple posts regarding this. I believe this started on Thursday 11/24. Hope this is resolved soon. Thanks

**Comment by cruise-insights** [comment] 2017-02-01 20:41
@jordiruiz  @,@wasp127,@ArinaHantsis @noanu 
Hi ,
 1) Inspect the export data functionality in browser.
2) Whenever you click , "export data " , in the networks tab, you will get an api call with title "uploads" 
  Just copy the response, if not possible then try copying the request and response headers of the api call.
And paste it here.

Also, please mention the type of connection used ( Import / Direct Query ).

Regards

**Comment by jordiruiz** [comment] 2017-02-02 19:09
Hi @cruise-insights ,

I can export data now, I'm sorry but I'm not sure when it started to work again for me.

**Comment by cruise-insights** [comment] 2017-02-06 12:38
@jordiruiz, @wasp127,@ArinaHantsis @noanu

Hi ,its an error that powerbi client api faces sometimes , generally 500.
we have reported it to the microsoft team that work with us  

Regards
Anurag Raj

**Comment by ali-hamud** [comment] 2017-02-06 14:34
@cruise-insights 
can you please repro the bug with Developer tools opened (F12 in chrome) and give us a Request ID.
RequestId can be found in a lot of requests as a header.

**Comment by cruise-insights** [comment] 2017-02-06 14:54
@ali-hamud 
Sure, trying to reproduce the bug .
Thanks,

**Comment by ali-hamud** [comment] 2017-03-16 08:57
Closing, because we could not repro the bug.
please re-open if you have repro steps.

**Closed by ali-hamud** 2017-03-16 08:57 UTC
Labels: Not Repro
